---
- hosts: all
  user: root
  become: true
  gather_facts: no

  tasks:
    - name: dis
#      command: echo "how are you"
      debug: msg="my name is sashi"
    - name: installing ntp
      yum: name="ntp"  state=present      
