---
- hosts: all
  user: root
  become: true
  gather_facts: no

  tasks:
    - name: Install http
      yum: name=httpd state=present
    - name: copy the index file    
      copy: src=/root/Ansible/index.html dest=/var/www/html/index.html
    - name: start service
      service: name=httpd enabled=yes state=started 
